name 'moodle_opsworks'
maintainer 'The Authors'
maintainer_email 'techsupport@itmasters.edu.au'
description 'Installs/Configures moodle_opsworks'
long_description 'Installs/Configures moodle_opsworks'
version '0.1.0'

depends 'memcached'
depends 'docker'
depends 's3_file'
depends 'oh_my_zsh'
depends 'xdebug'
